site_name: MkLorum
site_description: This is a trial test of mkdocs
site_url: null
repo_url: https://github.com/wickes1/my-first-mkdocs
# nav:
#   - Home: index.md
#   - About: about.md

theme:
  name: material
  favicon: img/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - footnotes
  # https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search:
      lang: en
      indexing: "full"
      prebuild_index: true
  - mermaid2:
      arguments:
        # test if its __palette_1 (dark) or __palette_2 (light)
        theme: |
          ^(JSON.parse(window.localStorage.getItem('/.__palette')).index == 1) ? 'dark' : 'light'
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - extra/refresh_on_toggle_dark_light.js
# extra:
#   version:
#     provider: mike
# theme:
#   name: mkdocs
#   # nav_style: dark
#   # nav_style: light
#   navigation_depth: 2
#   # locale: en
#   shortcuts:
#     help: 191 # ?
#     next: 78 # n
#     previous: 80 # p
#     search: 83 # s

#   highlightjs: true
#   hljs_languages:
#     - yaml
#     - rust

# theme:
#   name: readthedocs
#   highlightjs: true
#   analytics:
#     gtag: null
#   hljs_languages:
#     - yaml
#     - rust
